# Generated by Django 5.2 on 2025-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movieinfo_directed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="movieinfo",
            name="actors",
            field=models.ManyToManyField(
                related_name="movie_actors", to="movies.actor"
            ),
        ),
    ]
