# Generated by Django 5.2 on 2025-04-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_actor_movieinfo_actors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieinfo",
            name="censor_details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie",
                to="movies.censorinfo",
            ),
        ),
    ]
