# Generated by Django 5.2 on 2025-04-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_movieinfo_censor_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieinfo",
            name="censor_details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie",
                to="movies.censorinfo",
            ),
        ),
    ]
